name: RestaurantGuideFlutter
description: A new Flutter project. Created by Slidy

publish_to: 'none' 
version: 1.0.0+1

vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  transparent_image:
  dio:
  flutter_mobx:
  mobx:
  flutter_modular:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  mockito: 
  mobx_codegen:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
